// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "RLA)m#eoUk5~q@@Hy":
            case "I-Up":return img`
........................
........................
........................
........................
........................
........................
666666666666666666666666
699996699996699996699996
699996699996699996699996
699996699996699996699996
699996699996699996699996
666666666666666666666666
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
`;
            case "image1":
            case "I-Right":return img`
............666666......
............699996......
............699996......
............699996......
............699996......
............666666......
............666666......
............699996......
............699996......
............699996......
............699996......
............666666......
............666666......
............699996......
............699996......
............699996......
............699996......
............666666......
............666666......
............699996......
............699996......
............699996......
............699996......
............666666......
`;
            case "image2":
            case "I-Down":return img`
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
666666666666666666666666
699996699996699996699996
699996699996699996699996
699996699996699996699996
699996699996699996699996
666666666666666666666666
........................
........................
........................
........................
........................
........................
`;
            case "image3":
            case "I-Left":return img`
......666666............
......699996............
......699996............
......699996............
......699996............
......666666............
......666666............
......699996............
......699996............
......699996............
......699996............
......666666............
......666666............
......699996............
......699996............
......699996............
......699996............
......666666............
......666666............
......699996............
......699996............
......699996............
......699996............
......666666............
`;
            case "image5":
            case "T-Up":return img`
......cccccc......
......caaaac......
......caaaac......
......caaaac......
......caaaac......
......cccccc......
cccccccccccccccccc
caaaaccaaaaccaaaac
caaaaccaaaaccaaaac
caaaaccaaaaccaaaac
caaaaccaaaaccaaaac
cccccccccccccccccc
..................
..................
..................
..................
..................
..................
`;
            case "image6":
            case "T-Right":return img`
......cccccc......
......caaaac......
......caaaac......
......caaaac......
......caaaac......
......cccccc......
......cccccccccccc
......caaaaccaaaac
......caaaaccaaaac
......caaaaccaaaac
......caaaaccaaaac
......cccccccccccc
......cccccc......
......caaaac......
......caaaac......
......caaaac......
......caaaac......
......cccccc......
`;
            case "image7":
            case "T-Down":return img`
..................
..................
..................
..................
..................
..................
cccccccccccccccccc
caaaaccaaaaccaaaac
caaaaccaaaaccaaaac
caaaaccaaaaccaaaac
caaaaccaaaaccaaaac
cccccccccccccccccc
......cccccc......
......caaaac......
......caaaac......
......caaaac......
......caaaac......
......cccccc......
`;
            case "image8":
            case "T-Left":return img`
......cccccc......
......caaaac......
......caaaac......
......caaaac......
......caaaac......
......cccccc......
cccccccccccc......
caaaaccaaaac......
caaaaccaaaac......
caaaaccaaaac......
caaaaccaaaac......
cccccccccccc......
......cccccc......
......caaaac......
......caaaac......
......caaaac......
......caaaac......
......cccccc......
`;
            case "X%?75p":
            case "overlapCheck":return img`
2 2 2 2 2 2 
2 2 2 2 2 2 
2 2 2 2 2 2 
2 2 2 2 2 2 
2 2 2 2 2 2 
2 2 2 2 2 2 
`;
            case "image9":
            case "S-Up":return img`
......666666666666
......677776677776
......677776677776
......677776677776
......677776677776
......666666666666
666666666666......
677776677776......
677776677776......
677776677776......
677776677776......
666666666666......
..................
..................
..................
..................
..................
..................
`;
            case "image10":
            case "S-Right":return img`
......666666......
......677776......
......677776......
......677776......
......677776......
......666666......
......666666666666
......677776677776
......677776677776
......677776677776
......677776677776
......666666666666
............666666
............677776
............677776
............677776
............677776
............666666
`;
            case "image11":
            case "S-Down":return img`
..................
..................
..................
..................
..................
..................
......666666666666
......677776677776
......677776677776
......677776677776
......677776677776
......666666666666
666666666666......
677776677776......
677776677776......
677776677776......
677776677776......
666666666666......
`;
            case "image12":
            case "S-Left":return img`
666666............
677776............
677776............
677776............
677776............
666666............
666666666666......
677776677776......
677776677776......
677776677776......
677776677776......
666666666666......
......666666......
......677776......
......677776......
......677776......
......677776......
......666666......
`;
            case "image13":
            case "Z-Up":return img`
eeeeeeeeeeee......
e2222ee2222e......
e2222ee2222e......
e2222ee2222e......
e2222ee2222e......
eeeeeeeeeeee......
......eeeeeeeeeeee
......e2222ee2222e
......e2222ee2222e
......e2222ee2222e
......e2222ee2222e
......eeeeeeeeeeee
..................
..................
..................
..................
..................
..................
`;
            case "image14":
            case "Z-Right":return img`
............eeeeee
............e2222e
............e2222e
............e2222e
............e2222e
............eeeeee
......eeeeeeeeeeee
......e2222ee2222e
......e2222ee2222e
......e2222ee2222e
......e2222ee2222e
......eeeeeeeeeeee
......eeeeee......
......e2222e......
......e2222e......
......e2222e......
......e2222e......
......eeeeee......
`;
            case "image15":
            case "Z-Down":return img`
..................
..................
..................
..................
..................
..................
eeeeeeeeeeee......
e2222ee2222e......
e2222ee2222e......
e2222ee2222e......
e2222ee2222e......
eeeeeeeeeeee......
......eeeeeeeeeeee
......e2222ee2222e
......e2222ee2222e
......e2222ee2222e
......e2222ee2222e
......eeeeeeeeeeee
`;
            case "image16":
            case "Z-Left":return img`
......eeeeee......
......e2222e......
......e2222e......
......e2222e......
......e2222e......
......eeeeee......
eeeeeeeeeeee......
e2222ee2222e......
e2222ee2222e......
e2222ee2222e......
e2222ee2222e......
eeeeeeeeeeee......
eeeeee............
e2222e............
e2222e............
e2222e............
e2222e............
eeeeee............
`;
            case "image17":
            case "J-Up":return img`
cccccc............
c8888c............
c8888c............
c8888c............
c8888c............
cccccc............
cccccccccccccccccc
c8888cc8888cc8888c
c8888cc8888cc8888c
c8888cc8888cc8888c
c8888cc8888cc8888c
cccccccccccccccccc
..................
..................
..................
..................
..................
..................
`;
            case "image18":
            case "J-Right":return img`
......cccccccccccc
......c8888cc8888c
......c8888cc8888c
......c8888cc8888c
......c8888cc8888c
......cccccccccccc
......cccccc......
......c8888c......
......c8888c......
......c8888c......
......c8888c......
......cccccc......
......cccccc......
......c8888c......
......c8888c......
......c8888c......
......c8888c......
......cccccc......
`;
            case "image19":
            case "J-Down":return img`
..................
..................
..................
..................
..................
..................
cccccccccccccccccc
c8888cc8888cc8888c
c8888cc8888cc8888c
c8888cc8888cc8888c
c8888cc8888cc8888c
cccccccccccccccccc
............cccccc
............c8888c
............c8888c
............c8888c
............c8888c
............cccccc
`;
            case "image20":
            case "J-Left":return img`
......cccccc......
......c8888c......
......c8888c......
......c8888c......
......c8888c......
......cccccc......
......cccccc......
......c8888c......
......c8888c......
......c8888c......
......c8888c......
......cccccc......
cccccccccccc......
c8888cc8888c......
c8888cc8888c......
c8888cc8888c......
c8888cc8888c......
cccccccccccc......
`;
            case "image21":
            case "L-Up":return img`
............eeeeee
............e4444e
............e4444e
............e4444e
............e4444e
............eeeeee
eeeeeeeeeeeeeeeeee
e4444ee4444ee4444e
e4444ee4444ee4444e
e4444ee4444ee4444e
e4444ee4444ee4444e
eeeeeeeeeeeeeeeeee
..................
..................
..................
..................
..................
..................
`;
            case "image22":
            case "L-Right":return img`
......eeeeee......
......e4444e......
......e4444e......
......e4444e......
......e4444e......
......eeeeee......
......eeeeee......
......e4444e......
......e4444e......
......e4444e......
......e4444e......
......eeeeee......
......eeeeeeeeeeee
......e4444ee4444e
......e4444ee4444e
......e4444ee4444e
......e4444ee4444e
......eeeeeeeeeeee
`;
            case "image23":
            case "L-Down":return img`
..................
..................
..................
..................
..................
..................
eeeeeeeeeeeeeeeeee
e4444ee4444ee4444e
e4444ee4444ee4444e
e4444ee4444ee4444e
e4444ee4444ee4444e
eeeeeeeeeeeeeeeeee
eeeeee............
e4444e............
e4444e............
e4444e............
e4444e............
eeeeee............
`;
            case "image24":
            case "L-Left":return img`
eeeeeeeeeeee......
e4444ee4444e......
e4444ee4444e......
e4444ee4444e......
e4444ee4444e......
eeeeeeeeeeee......
......eeeeee......
......e4444e......
......e4444e......
......e4444e......
......e4444e......
......eeeeee......
......eeeeee......
......e4444e......
......e4444e......
......e4444e......
......e4444e......
......eeeeee......
`;
            case "iG)r=A-(c[u+VxjGb$Hw":
            case "bottom":return img`
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
2............................................................2
22222222222222222222222222222222222222222222222222222222222222
`;
            case "image4":
            case "O":return img`
4 4 4 4 4 4 4 4 4 4 4 4 
4 5 5 5 5 4 4 5 5 5 5 4 
4 5 5 5 5 4 4 5 5 5 5 4 
4 5 5 5 5 4 4 5 5 5 5 4 
4 5 5 5 5 4 4 5 5 5 5 4 
4 4 4 4 4 4 4 4 4 4 4 4 
4 4 4 4 4 4 4 4 4 4 4 4 
4 5 5 5 5 4 4 5 5 5 5 4 
4 5 5 5 5 4 4 5 5 5 5 4 
4 5 5 5 5 4 4 5 5 5 5 4 
4 5 5 5 5 4 4 5 5 5 5 4 
4 4 4 4 4 4 4 4 4 4 4 4 
`;
            case "|,t,8/ZF)k`U$AuNA1FW":
            case "backdrop":return img`
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccc
`;
            case "image29":
            case "O-Ghost":return img`
5 5 5 5 5 5 5 5 5 5 5 5 
5 . . . . 5 5 . . . . 5 
5 . . . . 5 5 . . . . 5 
5 . . . . 5 5 . . . . 5 
5 . . . . 5 5 . . . . 5 
5 5 5 5 5 5 5 5 5 5 5 5 
5 5 5 5 5 5 5 5 5 5 5 5 
5 . . . . 5 5 . . . . 5 
5 . . . . 5 5 . . . . 5 
5 . . . . 5 5 . . . . 5 
5 . . . . 5 5 . . . . 5 
5 5 5 5 5 5 5 5 5 5 5 5 
`;
            case "image25":
            case "I-Up-Ghost":return img`
........................
........................
........................
........................
........................
........................
999999999999999999999999
9....99....99....99....9
9....99....99....99....9
9....99....99....99....9
9....99....99....99....9
999999999999999999999999
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
`;
            case "image26":
            case "I-Right-Ghost":return img`
............999999......
............9....9......
............9....9......
............9....9......
............9....9......
............999999......
............999999......
............9....9......
............9....9......
............9....9......
............9....9......
............999999......
............999999......
............9....9......
............9....9......
............9....9......
............9....9......
............999999......
............999999......
............9....9......
............9....9......
............9....9......
............9....9......
............999999......
`;
            case "image27":
            case "I-Down-Ghost":return img`
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
999999999999999999999999
9....99....99....99....9
9....99....99....99....9
9....99....99....99....9
9....99....99....99....9
999999999999999999999999
........................
........................
........................
........................
........................
........................
`;
            case "image28":
            case "I-Left-Ghost":return img`
......999999............
......9....9............
......9....9............
......9....9............
......9....9............
......999999............
......999999............
......9....9............
......9....9............
......9....9............
......9....9............
......999999............
......999999............
......9....9............
......9....9............
......9....9............
......9....9............
......999999............
......999999............
......9....9............
......9....9............
......9....9............
......9....9............
......999999............
`;
            case "image30":
            case "T-Up-Ghost":return img`
......aaaaaa......
......a....a......
......a....a......
......a....a......
......a....a......
......aaaaaa......
aaaaaaaaaaaaaaaaaa
a....aa....aa....a
a....aa....aa....a
a....aa....aa....a
a....aa....aa....a
aaaaaaaaaaaaaaaaaa
..................
..................
..................
..................
..................
..................
`;
            case "image31":
            case "T-Right-Ghost":return img`
......aaaaaa......
......a....a......
......a....a......
......a....a......
......a....a......
......aaaaaa......
......aaaaaaaaaaaa
......a....aa....a
......a....aa....a
......a....aa....a
......a....aa....a
......aaaaaaaaaaaa
......aaaaaa......
......a....a......
......a....a......
......a....a......
......a....a......
......aaaaaa......
`;
            case "image32":
            case "T-Down-Ghost":return img`
..................
..................
..................
..................
..................
..................
aaaaaaaaaaaaaaaaaa
a....aa....aa....a
a....aa....aa....a
a....aa....aa....a
a....aa....aa....a
aaaaaaaaaaaaaaaaaa
......aaaaaa......
......a....a......
......a....a......
......a....a......
......a....a......
......aaaaaa......
`;
            case "image33":
            case "T-Left-Ghost":return img`
......aaaaaa......
......a....a......
......a....a......
......a....a......
......a....a......
......aaaaaa......
aaaaaaaaaaaa......
a....aa....a......
a....aa....a......
a....aa....a......
a....aa....a......
aaaaaaaaaaaa......
......aaaaaa......
......a....a......
......a....a......
......a....a......
......a....a......
......aaaaaa......
`;
            case "image34":
            case "S-Up-Ghost":return img`
......777777777777
......7....77....7
......7....77....7
......7....77....7
......7....77....7
......777777777777
777777777777......
7....77....7......
7....77....7......
7....77....7......
7....77....7......
777777777777......
..................
..................
..................
..................
..................
..................
`;
            case "image35":
            case "S-Right-Ghost":return img`
......777777......
......7....7......
......7....7......
......7....7......
......7....7......
......777777......
......777777777777
......7....77....7
......7....77....7
......7....77....7
......7....77....7
......777777777777
............777777
............7....7
............7....7
............7....7
............7....7
............777777
`;
            case "image36":
            case "S-Down-Ghost":return img`
..................
..................
..................
..................
..................
..................
......777777777777
......7....77....7
......7....77....7
......7....77....7
......7....77....7
......777777777777
777777777777......
7....77....7......
7....77....7......
7....77....7......
7....77....7......
777777777777......
`;
            case "image37":
            case "S-Left-Ghost":return img`
777777............
7....7............
7....7............
7....7............
7....7............
777777............
777777777777......
7....77....7......
7....77....7......
7....77....7......
7....77....7......
777777777777......
......777777......
......7....7......
......7....7......
......7....7......
......7....7......
......777777......
`;
            case "image38":
            case "Z-Up-Ghost":return img`
222222222222......
2....22....2......
2....22....2......
2....22....2......
2....22....2......
222222222222......
......222222222222
......2....22....2
......2....22....2
......2....22....2
......2....22....2
......222222222222
..................
..................
..................
..................
..................
..................
`;
            case "image39":
            case "Z-Right-Ghost":return img`
............222222
............2....2
............2....2
............2....2
............2....2
............222222
......222222222222
......2....22....2
......2....22....2
......2....22....2
......2....22....2
......222222222222
......222222......
......2....2......
......2....2......
......2....2......
......2....2......
......222222......
`;
            case "image40":
            case "Z-Down-Ghost":return img`
..................
..................
..................
..................
..................
..................
222222222222......
2....22....2......
2....22....2......
2....22....2......
2....22....2......
222222222222......
......222222222222
......2....22....2
......2....22....2
......2....22....2
......2....22....2
......222222222222
`;
            case "image41":
            case "Z-Left-Ghost":return img`
......222222......
......2....2......
......2....2......
......2....2......
......2....2......
......222222......
222222222222......
2....22....2......
2....22....2......
2....22....2......
2....22....2......
222222222222......
222222............
2....2............
2....2............
2....2............
2....2............
222222............
`;
            case "image42":
            case "J-Up-Ghost":return img`
888888............
8....8............
8....8............
8....8............
8....8............
888888............
888888888888888888
8....88....88....8
8....88....88....8
8....88....88....8
8....88....88....8
888888888888888888
..................
..................
..................
..................
..................
..................
`;
            case "image43":
            case "J-Right-Ghost":return img`
......888888888888
......8....88....8
......8....88....8
......8....88....8
......8....88....8
......888888888888
......888888......
......8....8......
......8....8......
......8....8......
......8....8......
......888888......
......888888......
......8....8......
......8....8......
......8....8......
......8....8......
......888888......
`;
            case "image44":
            case "J-Down-Ghost":return img`
..................
..................
..................
..................
..................
..................
888888888888888888
8....88....88....8
8....88....88....8
8....88....88....8
8....88....88....8
888888888888888888
............888888
............8....8
............8....8
............8....8
............8....8
............888888
`;
            case "image45":
            case "J-Left-Ghost":return img`
......888888......
......8....8......
......8....8......
......8....8......
......8....8......
......888888......
......888888......
......8....8......
......8....8......
......8....8......
......8....8......
......888888......
888888888888......
8....88....8......
8....88....8......
8....88....8......
8....88....8......
888888888888......
`;
            case "image46":
            case "L-Up-Ghost":return img`
............444444
............4....4
............4....4
............4....4
............4....4
............444444
444444444444444444
4....44....44....4
4....44....44....4
4....44....44....4
4....44....44....4
444444444444444444
..................
..................
..................
..................
..................
..................
`;
            case "image47":
            case "L-Right-Ghost":return img`
......444444......
......4....4......
......4....4......
......4....4......
......4....4......
......444444......
......444444......
......4....4......
......4....4......
......4....4......
......4....4......
......444444......
......444444444444
......4....44....4
......4....44....4
......4....44....4
......4....44....4
......444444444444
`;
            case "image48":
            case "L-Down-Ghost":return img`
..................
..................
..................
..................
..................
..................
444444444444444444
4....44....44....4
4....44....44....4
4....44....44....4
4....44....44....4
444444444444444444
444444............
4....4............
4....4............
4....4............
4....4............
444444............
`;
            case "image49":
            case "L-Left-Ghost":return img`
444444444444......
4....44....4......
4....44....4......
4....44....4......
4....44....4......
444444444444......
......444444......
......4....4......
......4....4......
......4....4......
......4....4......
......444444......
......444444......
......4....4......
......4....4......
......4....4......
......4....4......
......444444......
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
